# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/f110f8cd-9e71-46d4-7e17-364e69b15ee5/volume/rsync-recipes/sqlite-3.30.0-on-osx, last modified Fri Oct  4 12:35:31 2019
# ------------------------------------------------

package:
    name: sqlite
    version: 3.30.0
source:
    sha1: 785c0f6f00fe1871cb1dd97893267cb50db03b9b
    url: https://www.sqlite.org/2019/sqlite-autoconf-3300000.tar.gz
build:
    number: '0'
    run_exports:
        - sqlite >=3.30.0,<4.0a0
    string: ha441bb4_0
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_18
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - make 4.2.1 h3efe00b_1
    host:
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - ncurses 6.1 h0a44026_1
        - zlib 1.2.11 h1de35cc_3
    run:
        - libedit >=3.1.20181209,<3.2.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
