# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/cb6c4049-2f74-4c85-4975-d65750e6b798/volume/rsync-recipes/urllib3-1.24.2-python_3.7-on-osx, last modified Fri Apr 26 09:09:53 2019
# ------------------------------------------------

package:
    name: urllib3
    version: 1.24.2
source:
    sha256: 9a247273df709c4fedb38c711e44292304f73f39ab01beda9f6b9fc375669ac3
    url: https://pypi.io/packages/source/u/urllib3/urllib3-1.24.2.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/cb6c4049-2f74-4c85-4975-d65750e6b798/volume/urllib3_1556288030144/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1b h1de35cc_1
        - pip 19.0.3 py37_0
        - python 3.7.3 h359304d_0
        - readline 7.0 h1de35cc_5
        - setuptools 41.0.0 py37_0
        - sqlite 3.28.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - certifi
        - cryptography >=1.3.4
        - idna >=2.0.0
        - pyopenssl >=0.14
        - pysocks >=1.5.6,<2.0,!=1.5.7
        - python >=3.7,<3.8.0a0
test:
    imports:
        - urllib3
        - urllib3.contrib
        - urllib3.packages
        - urllib3.packages.backports
        - urllib3.packages.ssl_match_hostname
        - urllib3.util
about:
    dev_url: https://github.com/shazow/urllib3
    doc_url: https://urllib3.readthedocs.io/
    home: https://urllib3.readthedocs.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
        - sigmavirus24
