# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/rsync-recipes/python-3.7.4-on-osx, last modified Tue Aug 13 12:42:45 2019
# ------------------------------------------------

package:
    name: python
    version: 3.7.4
source:
    -   patches:
            - 0001-Add-Anaconda-Distribution-version-logic.patch
            - 0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0003-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0004-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0005-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0006-Support-cross-compiling-byte-code.patch
            - 0007-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0008-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0010-Win32-Do-not-download-externals.patch
            - 0011-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - 0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - 0013-Disable-new-dtags-in-unixccompiler.py.patch
            - 0014-Fix-cross-compilation-on-Debian-based-distros.patch
            - 0015-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
            - 0016-Unvendor-openssl.patch
            - 0017-Unvendor-sqlite3.patch
            - 0018-venv-Revert-a-change-from-https-github.com-python-cp.patch
            - 0019-Add-CondaEcosystemModifyDllSearchPath.patch
        sha256: fb799134b868199930b75f26678f18932214042639cd52b16da7fd134cd9b13f
        url: https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tar.xz
build:
    detect_binary_files_with_prefix: false
    ignore_run_exports:
        - bzip2
    number: '1'
    string: h359304d_1
requirements:
    build:
        - cctools 895 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_17
        - clangxx 4.0.1 1
        - clangxx_osx-64 4.0.1 h22b1bf0_17
        - compiler-rt 4.0.1 hcfea43d_1
        - ld64 274.2 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libiconv 1.15 hdd342a3_7
        - llvm 4.0.1 1
        - llvm-lto-tapi 4.0.1 1
        - make 4.2.1 h3efe00b_1
        - patch 2.7.6 h3efe00b_0
        - pkg-config 0.29.2 h3efe00b_8
    host:
        - bzip2 1.0.8 h1de35cc_0
        - ca-certificates 2019.5.15 1
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1c h1de35cc_1
        - readline 7.0 h1de35cc_5
        - sqlite 3.29.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - libcxx >=4.0.1
        - libffi >=3.2.1,<4.0a0
        - ncurses >=6.1,<7.0a0
        - openssl >=1.1.1c,<1.1.2a
        - readline >=7.0,<8.0a0
        - sqlite >=3.29.0,<4.0a0
        - tk >=8.6.8,<8.7.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - for f in ${PREFIX}/lib/python3.7/_sysconfig*.py; do echo "Checking $f:";
            if [[ `rg @ $f` ]]; then exit 1; fi; done
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
