# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/049526f0-222f-44b2-65a8-1a9f0a935be7/volume/rsync-recipes/requests-2.22.0-python_3.7-on-osx, last modified Mon Jun  3 09:50:21 2019
# ------------------------------------------------

package:
    name: requests
    version: 2.22.0
source:
    sha256: 11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4
    url: https://pypi.io/packages/source/r/requests/requests-2.22.0.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/049526f0-222f-44b2-65a8-1a9f0a935be7/volume/requests_1559573644197/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed -vv
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1c h1de35cc_1
        - pip 19.1.1 py37_0
        - python 3.7.3 h359304d_0
        - readline 7.0 h1de35cc_5
        - setuptools 41.0.1 py37_0
        - sqlite 3.28.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.9
        - python >=3.7,<3.8.0a0
        - urllib3 >=1.21.1,<1.25
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
