# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/3149ad1d-b98b-4800-5608-ee78071a1abe/volume/rsync-recipes/pip-19.3.1-python_3.7-on-osx, last modified Mon Oct 21 09:36:23 2019
# ------------------------------------------------

package:
    name: pip
    version: 19.3.1
source:
    sha256: 21207d76c1031e517668898a6b46a9fb1501c7a4710ef5dfd6a40ad9e6757ea7
    url: https://pypi.io/packages/source/p/pip/pip-19.3.1.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.main:main
    number: '0'
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.8.28 0
        - certifi 2019.9.11 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - python 3.7.4 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.4.0 py37_0
        - sqlite 3.30.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
