# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/af9f6011-2446-472e-76cb-953c0f7aa07d/volume/rsync-recipes/wheel-0.33.6-python_3.7-on-osx, last modified Mon Sep 23 13:26:16 2019
# ------------------------------------------------

package:
    name: wheel
    version: 0.33.6
source:
    sha256: 10c9da68765315ed98850f8e048347c3eb06dd81822dc2ab1d4fde9dc9702646
    url: https://pypi.io/packages/source/w/wheel/wheel-0.33.6.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.5.15 1
        - certifi 2019.9.11 py37_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_1
        - python 3.7.4 h359304d_1
        - readline 7.0 h1de35cc_5
        - setuptools 41.2.0 py37_0
        - sqlite 3.29.0 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
